// (c)2022 cndrbrbr 
'use strict';
const blocks = {
  wool: {
    red: "red_wool.png",
    black: "black_wool.png",
    brown: "brown_wool.png",
    cyan: "cyan_wool.png",
    lightblue: "light_blue_wool.png",
    lightgray: "light_gray_wool.png",
    gray: "gray_wool.png",
    lime: "lime_wool.png",
    green: "green_wool.png",
    magenta: "magenta_wool.png",
    orange: "orange_wool.png",
    pink: "pink_wool.png",
    purple: "purple_wool.png",
    white: "white_wool.png",
    yellow: "yellow_wool.png",
    blue: "blue_wool.png"
  },
  andesite : "andesite.png",
  air : "air.png",
  anvil : "anvil.png",
  beacon : "beacon.png",
  bedrock : "bedrock.png",
  cobblestone : "cobblestone.png",
  diamond : "diamond_block.png",
  diamond_ore : "diamond_ore.png",
  diorite : "diorite.png",
  dirt : "dirt.png",
  emerald : "emerald_block.png",
  emerald_ore : "emerald_ore.png",
  endstone : "end_stone.png",
  farmland : "farmland.png",
  ice : "ice.png",
  glass : "glass.png",
  glowstone : "glowstone.png",
  gold : "gold_block.png",
  gold_ore : "gold_oreng",
  gravel : "gravel.png",
  iron : "iron_block.png",
  iron_bars : "iron_bars.png",
  iron_ore : "iron_ore.png",
  mushroom_red : "red_mushroom_block.png",
  redstone_lamp : "redstone_lamp_on.png",
  redstone : "redstone_block.png",
  sand : "sand.png",
  sandstone : "sandstone.png",
  snow : "snow.png",
  quartz: "quartz_block_side.png",
  dirt: "grass_block_side.png",
  gold: "gold_block.png"
};
module.exports = blocks;
