// (c)2022 cndrbrbr — updated 2026 for JSMN uppercase material names
'use strict';

// Maps both lowercase (ScriptCraft legacy) and JSMN uppercase Bukkit Material names to PNG textures.
const blocks = {
  // JSMN uppercase (Bukkit Material enum)
  AIR:           'air.png',
  DIRT:          'dirt.png',
  GRASS_BLOCK:   'grass_block_side.png',
  STONE:         'stone.png',
  COBBLESTONE:   'cobblestone.png',
  QUARTZ_BLOCK:  'quartz_block_side.png',
  SANDSTONE:     'sandstone.png',
  DIORITE:       'diorite.png',
  ANDESITE:      'andesite.png',
  GRANITE:       'andesite.png',       // reuse until granite.png added
  GLASS:         'glass.png',
  ICE:           'ice.png',
  SNOW_BLOCK:    'snow.png',
  GRAVEL:        'gravel.png',
  GLOWSTONE:     'glowstone.png',
  BEACON:        'beacon.png',
  OBSIDIAN:      'bedrock.png',        // reuse until obsidian.png added
  DIAMOND_BLOCK: 'diamond_block.png',
  EMERALD_BLOCK: 'emerald_block.png',
  IRON_BLOCK:    'iron_block.png',
  GOLD_BLOCK:    'gold_block.png',
  SAND:          'sand.png',
  BEDROCK:       'bedrock.png',
  END_STONE:     'end_stone.png',
  RED_WOOL:      'red_wool.png',
  ORANGE_WOOL:   'orange_wool.png',
  YELLOW_WOOL:   'yellow_wool.png',
  LIME_WOOL:     'lime_wool.png',
  GREEN_WOOL:    'green_wool.png',
  BLUE_WOOL:     'blue_wool.png',
  PURPLE_WOOL:   'purple_wool.png',
  MAGENTA_WOOL:  'magenta_wool.png',
  PINK_WOOL:     'pink_wool.png',
  WHITE_WOOL:    'white_wool.png',

  // Legacy lowercase (ScriptCraft / old saved files)
  air:           'air.png',
  andesite:      'andesite.png',
  anvil:         'anvil.png',
  beacon:        'beacon.png',
  bedrock:       'bedrock.png',
  cobblestone:   'cobblestone.png',
  diamond:       'diamond_block.png',
  diamond_ore:   'diamond_ore.png',
  diorite:       'diorite.png',
  dirt:          'dirt.png',
  emerald:       'emerald_block.png',
  emerald_ore:   'emerald_ore.png',
  endstone:      'end_stone.png',
  farmland:      'farmland.png',
  glass:         'glass.png',
  glowstone:     'glowstone.png',
  gold:          'gold_block.png',
  gravel:        'gravel.png',
  ice:           'ice.png',
  iron:          'iron_block.png',
  iron_bars:     'iron_bars.png',
  iron_ore:      'iron_ore.png',
  quartz:        'quartz_block_side.png',
  redstone:      'redstone_block.png',
  redstone_lamp: 'redstone_lamp_on.png',
  sand:          'sand.png',
  sandstone:     'sandstone.png',
  snow:          'snow.png',
  wool: {
    red:       'red_wool.png',
    blue:      'blue_wool.png',
    green:     'green_wool.png',
    lime:      'lime_wool.png',
    orange:    'orange_wool.png',
    white:     'white_wool.png',
    yellow:    'yellow_wool.png',
    purple:    'purple_wool.png',
    magenta:   'magenta_wool.png',
    pink:      'pink_wool.png',
    black:     'black_wool.png',
    brown:     'brown_wool.png',
    cyan:      'cyan_wool.png',
    lightblue: 'light_blue_wool.png',
    lightgray: 'light_gray_wool.png',
    gray:      'gray_wool.png'
  }
};

module.exports = blocks;
